[variables]
NIXPACKS_BUILD_CMD = "cd api-nestjs && rm -f package-lock.json && npm install --legacy-peer-deps && npx prisma generate && npm run build"
NIXPACKS_START_CMD = "cd api-nestjs && npm run prisma:deploy && npm run start:prod"

[phases.setup]
nixPkgs = ['nodejs_20', 'npm-10_x']

[phases.install]
cmds = [
  'cd api-nestjs',
  'rm -f package-lock.json',
  'npm install --legacy-peer-deps',
  'npx prisma generate'
]

[phases.build]
cmds = [
  'cd api-nestjs',
  'npm run build'
]

[start]
cmd = 'cd api-nestjs && npm run prisma:deploy && npm run start:prod'